#!/bin/sh
sudo echo "if ! [ -z "$BASH_VERSION" -o -z "$PS1" -o -n "$last_command_started_cache" ]; then" >> /etc/bash.bashrc
sudo echo ". /usr/share/undistract-me/long-running.bash" >> /etc/bash.bashrc
sudo echo "notify_when_long_running_commands_finish_install" >> /etc/bash.bashrc
sudo echo "fi" >> /etc/bash.bashrc
