#!/bin/sh
echo "if ! [ -z "$BASH_VERSION" -o -z "$PS1" -o -n "$last_command_started_cache" ]; then" >> ~/.bashrc
echo ". /usr/share/undistract-me/long-running.bash" >> ~/.bashrc
echo "notify_when_long_running_commands_finish_install" >> ~/.bashrc
echo "fi" >> ~/.bashrc
